# Site setings
name: 'Jackson Borneman'
description: 'Student'
meta_description: 'Learning to build the next generation of computer systems'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.webp'
  greetings: "Hello, I'm Jackson Borneman. I do various computer projects around the US."
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://jaxb.net
disqus: 'jaxb-net'
mailchimp_url: 
#'//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
# Add your GA Tracking Id
ga_analytics: UA-179693434-1

# Contact form setings
email: me@jaxb.net
contact_page_description: "Feel feel to drop me a line with the included form or via email me @ jaxb . net"
thankyou_page_description: "Your message has been successfully sent. I will contact you very soon!"

# Social links
twitter: 'jaxb__'
facebook:
github: 'jax-b'
codepen: 
dribbble: 
medium: 
instagram: 
pinterest: 
linkedin: 'jacksonborneman'
producthunt: 
quora: 

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  # - text: Projects
  #   url: /projects
  - text: Contact Me
    url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  
# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

defaults:
  -
    scope:
      path: "_slides" 
    values:
      layout: "iframe"

collections:
  slides:
    output: true

